Add missing include in src/FreeType/ftfuncs.c
Fixes compiler warning:
../../../src/FreeType/ftfuncs.c: In function 'restrict_code_range_by_str':
../../../src/FreeType/ftfuncs.c:2081: warning: implicit declaration of function 'isspace'