Do not call FT_Get_BDF_Charset_ID() if configured with --disable-bdfformat
When I configure libXfont-1.3.2 with --disable-bdfformat and link it against
FreeType that is built without BDF support, I get the following link error:

libXfont.so: undefined reference to ‘FT_Get_BDF_Charset_ID’

I fixed it by checking XFONT_BDFFORMAT and if BDF support is disabled, the call
to FT_Get_BDF_Charset_ID() is omitted and the result code is set as if the call
had failed.

Signed-off-by: James Cloos <cloos@jhcloos.com>